### PR TITLE
New coverage eligibility request v5

### PR DESCRIPTION
**Pull request by PatrickWaweru**
New coverage eligibility request v5

### CODE REVIEW

**Review by patryllus — CHANGES_REQUESTED** [review]
file:///home/patrick/Pictures/Screenshots/Screenshot%20from%202024-08-20%2012-41-15.png

Kindly use the Social Health Authority Unique Identification Number instead of the SHA number if you are looking for CR number

**Comment by PatrickWaweru** [comment]
> file:///home/patrick/Pictures/Screenshots/Screenshot%20from%202024-08-20%2012-41-15.png
> 
> Kindly use the Social Health Authority Unique Identification Number instead of the SHA number if you are looking for CR number

Ok i have fixed it

**Review by njorocs — APPROVED** [review]
lgtm

**Review by PatrickWaweru — COMMENTED** [review]
Done

**Comment by ojwanganto** [comment]
> file:///home/patrick/Pictures/Screenshots/Screenshot%20from%202024-08-20%2012-41-15.png
> 
> Kindly use the Social Health Authority Unique Identification Number instead of the SHA number if you are looking for CR number

Will that name not be too long!

**Review by patryllus — APPROVED** [review]
Looks okay. Kindly confirm from Jacinta that CR id id used to pull the policy

**Pull request merged**
